sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ***
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5***p8xau4V
    access-key-secret: eC7qMElzR6****LQzBstiteK
    bucket-name: sky-mju
  redis:
    host: localhost
    port: 6379
    password: ***
    database: 1
  wechat:
    appid: wx4d****e9182
    secret: 6ff8*********456afb
    notify-url:  https://7ee893bb.r9.cpolar.top/notify/paySuccess
    refund-notify-url:  https://7ee893bb.r9.cpolar.top/notify/refundSuccess
