sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ygf
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDLxZoovH2M6p8xau4V
    access-key-secret: eC7qMElzR6G8ksk30SRKLQzBstiteK
    bucket-name: sky-mju
  redis:
    host: localhost
    port: 6379
    password: ygf
    database: 1
  wechat:
    appid: wx4d311710633e9182
    secret: 6ff85ab0915a969e0d9c9de5f3456afb
    notify-url:  https://7ee893bb.r9.cpolar.top/notify/paySuccess
    refund-notify-url:  https://7ee893bb.r9.cpolar.top/notify/refundSuccess